import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialPortalSchema1779473729832 implements MigrationInterface {
    name = 'InitialPortalSchema1779473729832'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "users_admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying NOT NULL DEFAULT 'Admin', "role" character varying NOT NULL DEFAULT 'admin', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "last_login_ip" character varying, "two_fa_enabled" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_23b4b9ed689230fb3af339412ef" UNIQUE ("email"), CONSTRAINT "PK_4f0f50d9922a0ed51c214f5556b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_code" character varying NOT NULL, "magnus_username" character varying, "full_name" character varying NOT NULL, "company_name" character varying, "email" character varying, "phone" character varying, "telegram" character varying, "country" character varying, "signup_ip" character varying, "status" character varying NOT NULL DEFAULT 'active', "risk_level" character varying NOT NULL DEFAULT 'Low', "kyc_status" character varying NOT NULL DEFAULT 'not_required', "last_login_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_acd5656a9fa7cf04125f0848165" UNIQUE ("customer_code"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_acd5656a9fa7cf04125f084816" ON "customers" ("customer_code") `);
        await queryRunner.query(`CREATE TABLE "recharges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recharge_code" character varying NOT NULL, "customer_id" uuid NOT NULL, "invoice_id" character varying, "invoice_number" character varying, "magnus_username" character varying, "amount" numeric(18,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "crypto_amount" numeric(18,8) NOT NULL DEFAULT '0', "crypto_coin" character varying NOT NULL DEFAULT 'USDT', "crypto_network" character varying NOT NULL DEFAULT 'TRC20', "wallet_address" character varying, "tx_hash" character varying, "payment_gateway" character varying NOT NULL DEFAULT 'Manual', "payment_date" TIMESTAMP, "magnus_credit_added" numeric(18,2), "magnus_reference_id" character varying, "magnus_credited_at" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'pending_payment', "reconciled" boolean NOT NULL DEFAULT false, "reconciliation_note" text, "admin_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a536b9aa3dad7a3e57d4fab85c4" UNIQUE ("recharge_code"), CONSTRAINT "PK_19efa203cefcf8cf544d7ea7e33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a536b9aa3dad7a3e57d4fab85c" ON "recharges" ("recharge_code") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying NOT NULL, "customer_id" character varying NOT NULL, "recharge_id" character varying, "customer_name" character varying NOT NULL, "customer_email" character varying, "customer_country" character varying, "customer_company" character varying, "service_name" character varying NOT NULL DEFAULT 'SaaS Platform Usage Credits', "service_description" text NOT NULL DEFAULT 'Prepaid credits for usage of Axistra cloud software platform and related digital services.', "amount" numeric(18,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "payment_method" character varying, "crypto_coin" character varying, "crypto_network" character varying, "tx_hash" character varying, "status" character varying NOT NULL DEFAULT 'unpaid', "issued_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE TABLE "crypto_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recharge_id" character varying NOT NULL, "customer_id" character varying NOT NULL, "crypto_amount" numeric(18,8) NOT NULL, "coin" character varying NOT NULL DEFAULT 'USDT', "network" character varying NOT NULL DEFAULT 'TRC20', "receiving_wallet" character varying, "tx_hash" character varying NOT NULL, "wallet_balance_after" numeric(18,8), "aed_rate_at_payment" numeric(12,4), "aed_value" numeric(18,2), "status" character varying NOT NULL DEFAULT 'received', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ea984bfd1336c3298198a2d6783" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d30f6a483a032bc38d519047ad" ON "crypto_transactions" ("tx_hash") `);
        await queryRunner.query(`CREATE TABLE "treasury_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recharge_id" character varying NOT NULL, "customer_id" character varying NOT NULL, "total_usdt_received" numeric(18,8) NOT NULL DEFAULT '0', "receiving_wallet" character varying, "receive_tx_hash" character varying, "transferred_to_okx" boolean NOT NULL DEFAULT false, "okx_deposit_tx_hash" character varying, "okx_account_reference" character varying, "okx_transfer_date" TIMESTAMP, "converted_to_aed" boolean NOT NULL DEFAULT false, "usdt_converted" numeric(18,8), "okx_conversion_rate" numeric(12,4), "aed_received" numeric(18,2), "conversion_date" TIMESTAMP, "transferred_to_wio" boolean NOT NULL DEFAULT false, "wio_bank_reference" character varying, "wio_deposit_date" TIMESTAMP, "wio_aed_amount" numeric(18,2), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_15e5349eb0e63c75ef678e08882" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expense_date" TIMESTAMP NOT NULL, "vendor_name" character varying NOT NULL, "category" character varying NOT NULL, "amount" numeric(18,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'AED', "payment_method" character varying NOT NULL DEFAULT 'Bank', "paid_in_usdt" boolean NOT NULL DEFAULT false, "vendor_wallet" character varying, "crypto_network" character varying, "tx_hash" character varying, "aed_rate" numeric(12,4), "aed_value" numeric(18,2), "bank_reference" character varying, "receipt_url" character varying, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "compliance_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" character varying NOT NULL, "risk_level" character varying NOT NULL DEFAULT 'Low', "action" character varying NOT NULL, "notes" text, "blocked" boolean NOT NULL DEFAULT false, "high_volume_flag" boolean NOT NULL DEFAULT false, "refund_amount" character varying, "refund_currency" character varying, "kyc_requested_at" TIMESTAMP, "document_url" character varying, "admin_comment" text, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0f10ef25e2593d957c2a38873c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor_id" character varying, "actor_email" character varying, "action" character varying NOT NULL, "entity_type" character varying, "entity_id" character varying, "details" text, "ip_address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "magnus_sync_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recharge_id" character varying, "magnus_username" character varying, "action" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'success', "request_payload" text, "response_payload" text, "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d16f3f7696ed8b07456c5b5935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kyc_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" character varying NOT NULL, "document_type" character varying NOT NULL, "file_name" character varying NOT NULL, "file_url" character varying, "status" character varying NOT NULL DEFAULT 'submitted', "admin_comment" text, "reviewed_by" character varying, "reviewed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02e49877f1578e6285f84e57ab6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("key" character varying NOT NULL, "value" text NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c8639b7626fa94ba8265628f214" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying NOT NULL, "last_name" character varying, "email" character varying NOT NULL, "company" character varying, "phone" character varying, "message" text, "source" character varying NOT NULL DEFAULT 'website', "status" character varying NOT NULL DEFAULT 'new', "ip_address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3eea7add0e16594dba102716c" ON "leads" ("email") `);
        await queryRunner.query(`ALTER TABLE "recharges" ADD CONSTRAINT "FK_2d9148851483713298bbb2e64d9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "recharges" DROP CONSTRAINT "FK_2d9148851483713298bbb2e64d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3eea7add0e16594dba102716c"`);
        await queryRunner.query(`DROP TABLE "leads"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "kyc_documents"`);
        await queryRunner.query(`DROP TABLE "magnus_sync_logs"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "compliance_logs"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TABLE "treasury_movements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d30f6a483a032bc38d519047ad"`);
        await queryRunner.query(`DROP TABLE "crypto_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a536b9aa3dad7a3e57d4fab85c"`);
        await queryRunner.query(`DROP TABLE "recharges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acd5656a9fa7cf04125f084816"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "users_admin"`);
    }

}
